version: '3.4'

services:
  medcattrainer:
    container_name: medcattrainer
    hostname: medcat
    restart: always
    image: medcattrainer_medcattrainer
    volumes:
      - api-media:/home/api/media
      - api-static:/home/api/static
      - api-db:/home/api/db
    expose:
      - "8000"
    env_file:
      - ./envs/env
    command: /home/run.sh
  nginx:
    container_name: medcattrainer_nginx
    restart: always
    image: medcattrainer_nginx
    restart: always
    volumes:
      - api-media:/home/api/media
      - api-static:/home/api/static
    ports:
      - "${MCTRAINER_PORT:-8001}:8000"
    depends_on:
      - medcattrainer
volumes:
      api-media:
      api-static:
      api-db:
