# Generated by Django 2.2 on 2019-04-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainerapp', '0002_auto_20190428_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='usecase',
            name='type',
            field=models.CharField(default='all', max_length=50),
        ),
    ]
