# Generated by Django 2.2 on 2019-05-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainerapp', '0006_auto_20190428_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usecase',
            name='folder',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
