# Generated by Django 2.2 on 2019-05-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainerapp', '0008_auto_20190513_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='value',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
