# Generated by Django 2.2 on 2019-05-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainerapp', '0009_add_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usecase',
            name='filters',
            field=models.ManyToManyField(blank=True, to='trainerapp.Filter'),
        ),
    ]
