# Generated by Django 2.2.5 on 2019-09-23 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotatedentity',
            name='correct',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='annotatedentity',
            name='validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='metaannotation',
            name='validated',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='projectannotateentities',
            name='require_entity_validation',
            field=models.BooleanField(default=False),
        ),
    ]
