# Generated by Django 2.2.3 on 2019-09-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190923_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotatedentity',
            name='correct',
        ),
        migrations.AddField(
            model_name='annotatedentity',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
