# Generated by Django 2.2.5 on 2019-09-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190924_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='validated_documents',
            field=models.ManyToManyField(blank=True, default=None, to='api.Document'),
        ),
    ]
