# Generated by Django 2.2.3 on 2019-09-27 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_concept_icd10'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='cdb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ConceptDB'),
        ),
    ]
