# Generated by Django 2.2.3 on 2019-09-29 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_annotatedentity_manually_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
