# Generated by Django 2.2.3 on 2019-09-29 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_document_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotatedentity',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
