# Generated by Django 2.2.3 on 2019-09-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_annotatedentity_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectannotateentities',
            name='cdb_search_filter',
            field=models.ManyToManyField(blank=True, null=True, to='api.ConceptDB'),
        ),
    ]
