# Generated by Django 2.2.3 on 2019-10-01 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_projectannotateentities_cdb_search_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptdb',
            name='use_for_training',
            field=models.BooleanField(default=True),
        ),
    ]
