# Generated by Django 2.2.5 on 2019-10-01 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_conceptdb_use_for_training'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectannotateentities',
            name='cdb_search_filter',
            field=models.ManyToManyField(blank=True, default=None, to='api.ConceptDB'),
        ),
    ]
