# Generated by Django 2.2.3 on 2019-10-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20191001_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptdb',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
