# Generated by Django 2.2.3 on 2019-10-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_conceptdb_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectannotateentities',
            name='tasks',
            field=models.ManyToManyField(blank=True, default=None, to='api.MetaTask'),
        ),
        migrations.AlterField(
            model_name='metaannotation',
            name='acc',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='metaannotation',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
