# Generated by Django 2.2.3 on 2019-10-02 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20191002_2306'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Link',
        ),
    ]
