# Generated by Django 2.2.3 on 2019-10-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_delete_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotatedentity',
            name='killed',
            field=models.BooleanField(default=False),
        ),
    ]
