# Generated by Django 2.2.9 on 2020-01-31 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_concept_opcs4'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICDCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('desc', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='OPCSCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('desc', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='concept',
            name='icd10',
        ),
        migrations.RemoveField(
            model_name='concept',
            name='opcs4',
        ),
        migrations.AddField(
            model_name='concept',
            name='icd10',
            field=models.ManyToManyField(blank=True, default=None, related_name='concept', to='api.ICDCode'),
        ),
        migrations.AddField(
            model_name='concept',
            name='opcs4',
            field=models.ManyToManyField(blank=True, default=None, related_name='concept', to='api.OPCSCode'),
        ),
    ]
