# Generated by Django 2.2.3 on 2020-02-04 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20200131_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metatask',
            name='default',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.MetaTaskValue'),
        ),
    ]
