# Generated by Django 2.2.9 on 2020-02-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20200208_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectannotateentities',
            name='clinical_coding_project',
            field=models.BooleanField(default=False),
        ),
    ]
