# Generated by Django 2.2.9 on 2020-02-08 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20200208_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotatedentity',
            name='icdCode',
        ),
        migrations.RemoveField(
            model_name='annotatedentity',
            name='opcsCode',
        ),
        migrations.AddField(
            model_name='annotatedentity',
            name='icd_Code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ICDCode'),
        ),
        migrations.AddField(
            model_name='annotatedentity',
            name='opcs_Code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.OPCSCode'),
        ),
    ]
