# Generated by Django 2.2.9 on 2020-02-08 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20200208_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotatedentity',
            name='icd_Code',
        ),
        migrations.RemoveField(
            model_name='annotatedentity',
            name='opcs_Code',
        ),
        migrations.AddField(
            model_name='annotatedentity',
            name='icd_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ICDCode'),
        ),
        migrations.AddField(
            model_name='annotatedentity',
            name='opcs_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.OPCSCode'),
        ),
    ]
