# Generated by Django 2.2.9 on 2020-02-12 00:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20200208_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotatedentity',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 12, 0, 17, 34, 144415)),
        ),
    ]
