# Generated by Django 2.2.9 on 2020-02-12 00:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20200212_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotatedentity',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0)),
        ),
    ]
