# Generated by Django 2.2.9 on 2020-02-12 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20200212_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotatedentity',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
