# Generated by Django 2.2.11 on 2020-03-20 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20200320_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectannotateentities',
            name='concept_db',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ConceptDB'),
        ),
    ]
