# Generated by Django 2.2.11 on 2020-04-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20200320_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='cui',
            field=models.CharField(max_length=100),
        ),
    ]
