# Generated by Django 2.2.12 on 2020-04-16 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_project_cuis_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectannotateentities',
            name='restrict_concept_lookup',
            field=models.BooleanField(default=False),
        ),
    ]
