# Generated by Django 2.2.12 on 2020-05-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_projectannotateentities_restrict_concept_lookup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cuis_file',
            field=models.FileField(blank=True, help_text='A file containing a JSON formatted list of CUI code strings, i.e. ["S-1234","S-54321"]', null=True, upload_to=''),
        ),
    ]
