# Generated by Django 2.2.12 on 2020-05-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_auto_20200519_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectannotateentities',
            name='add_new_entities',
            field=models.BooleanField(default=False, help_text='allow the creation of new terms to be added to the CDB'),
        ),
        migrations.AlterField(
            model_name='projectannotateentities',
            name='clinical_coding_project',
            field=models.BooleanField(default=False, help_text='customised UI for the clinical coding (ICD-10/OPCS-4 use case'),
        ),
        migrations.AlterField(
            model_name='projectannotateentities',
            name='require_entity_validation',
            field=models.BooleanField(default=True, help_text='Entities appear grey and are required to be validated before submission'),
        ),
        migrations.AlterField(
            model_name='projectannotateentities',
            name='restrict_concept_lookup',
            field=models.BooleanField(default=False, help_text='users can only select terms from the list configured for the project, i.e. either from the cuis or cuis_file lists.'),
        ),
        migrations.AlterField(
            model_name='projectannotateentities',
            name='train_model_on_submit',
            field=models.BooleanField(default=True, help_text='active learning - configured CDB is trainedon each submit'),
        ),
    ]
