# Generated by Django 2.2.12 on 2020-05-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_auto_20200520_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectannotateentities',
            name='clinical_coding_project',
            field=models.BooleanField(default=False, help_text='customised UI for the clinical coding (ICD-10/OPCS-4) use case'),
        ),
    ]
