# Generated by Django 2.2.12 on 2020-06-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_projectannotateentities_terminate_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectannotateentities',
            name='terminate_available',
            field=models.BooleanField(default=True, help_text='enable the option to terminate concepts.'),
        ),
    ]
