# Generated by Django 2.2.12 on 2020-08-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_auto_20200603_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectannotateentities',
            name='add_new_entities',
            field=models.BooleanField(default=False, help_text='Allow the creation of new terms to be added to the CDB'),
        ),
        migrations.AlterField(
            model_name='projectannotateentities',
            name='restrict_concept_lookup',
            field=models.BooleanField(default=False, help_text='Users can only select terms from the list configured for the project, i.e. either from the cuis or cuis_file lists.'),
        ),
        migrations.AlterField(
            model_name='projectannotateentities',
            name='terminate_available',
            field=models.BooleanField(default=True, help_text='Enable the option to terminate concepts.'),
        ),
        migrations.AlterField(
            model_name='projectannotateentities',
            name='train_model_on_submit',
            field=models.BooleanField(default=True, help_text='Active learning - configured CDB is trained on each submit'),
        ),
    ]
