# Generated by Django 2.0 on 2021-01-12 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_auto_20200802_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='cui',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='concept',
            name='pretty_name',
            field=models.CharField(db_index=True, max_length=300),
        ),
    ]
