# Generated by Django 2.0 on 2021-02-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_projectcuicounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotatedentity',
            name='irrelevant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectannotateentities',
            name='irrelevant_available',
            field=models.BooleanField(default=False, help_text='Enable the option to add the irrelevant button.'),
        ),
    ]
