# Generated by Django 2.0 on 2021-02-02 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_auto_20210202_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tuis',
        ),
    ]
