# Generated by Django 2.2.18 on 2021-02-11 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_remove_project_tuis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='cdb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ConceptDB'),
        ),
    ]
