# Generated by Django 2.2.18 on 2021-02-16 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_auto_20210216_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectannotateentities',
            name='clinical_coding_project',
        ),
    ]
