# Generated by Django 2.2.9 on 2021-04-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_remove_concept_vocab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='cui',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
