# Generated by Django 2.2.9 on 2021-04-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_auto_20210417_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectannotateentities',
            name='restrict_concept_lookup',
            field=models.BooleanField(default=False, help_text='Users can only search for concept terms from the list configured for the project, i.e. either from the cuis or cuis_file lists.'),
        ),
    ]
