# Generated by Django 2.2.9 on 2021-09-21 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_auto_20210705_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotatedentity',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectannotateentities',
            name='enable_entity_annotation_comments',
            field=models.BooleanField(default=False, help_text='Enable to allow annotators to leave comments for each annotation'),
        ),
    ]
