# Generated by Django 2.2.9 on 2021-10-08 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_auto_20210921_0022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annotatedentity',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='entityrelation',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='relation',
            options={'ordering': ['id']},
        ),
    ]
