# Generated by Django 2.2.24 on 2021-10-22 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_auto_20211008_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concept',
            old_name='tui',
            new_name='type_ids',
        ),
    ]
