# Generated by Django 2.2.24 on 2022-04-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_project_annotation_guideline_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='cui',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
