# Generated by Django 2.2.24 on 2022-06-06 11:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_auto_20220426_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptdb',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_-]*$', 'Only alpahanumeric characters, -, _ are allowed for CDB names')]),
        ),
    ]
