# Generated by Django 2.2.24 on 2022-06-06 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_auto_20220606_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectannotateentities',
            name='concept_db',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ConceptDB'),
        ),
    ]
