# Generated by Django 2.2.28 on 2023-01-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_auto_20221129_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportedProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer_export_file', models.FileField(help_text='Previously exported MedCATtrainer .json file', upload_to='')),
            ],
        ),
    ]
