# Generated by Django 2.2.28 on 2023-01-24 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_exportedproject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Concept',
        ),
    ]
