# Generated by Django 2.2.28 on 2023-02-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_delete_concept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectannotateentities',
            name='restrict_concept_lookup',
            field=models.BooleanField(default=False, help_text='Users can only search for concept terms from the list configured for the project, i.e. either from the cuis or cuis_file lists. Checking this when bothcuis and cuis_file are empty does nothing. If "add new entities" is available & added, and cuis or cuis_fileis non-empty the new CUI will be added.'),
        ),
    ]
