# Generated by Django 2.2.28 on 2023-07-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_auto_20230711_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='annotation_classification',
            field=models.BooleanField(default=False, help_text='If these project annotations are suitable for training a general purpose model. If in doubt uncheck this.'),
        ),
    ]
