# Generated by Django 2.2.28 on 2023-09-21 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_auto_20230711_1654'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectCuiCounter',
        ),
    ]
