# Generated by Django 2.2.28 on 2023-10-22 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_delete_projectcuicounter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name_generated', models.TextField(help_text='report name that links this metrics report to a previously ran bg task')),
                ('report_name', models.TextField(help_text='A user specified report name that should be more user friendly than the generated one')),
                ('report', models.FileField(help_text='the outputted metrics for configured', upload_to='')),
                ('projects', models.ManyToManyField(blank=True, null=True, to='api.ProjectAnnotateEntities')),
            ],
        ),
        migrations.DeleteModel(
            name='MedCATModel',
        ),
    ]
