# Generated by Django 2.2.28 on 2023-12-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_auto_20231022_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmetrics',
            name='projects',
            field=models.ManyToManyField(blank=True, to='api.ProjectAnnotateEntities'),
        ),
    ]
