# Generated by Django 2.2.28 on 2024-02-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_auto_20231022_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opcscode',
            name='cdb',
        ),
        migrations.RemoveField(
            model_name='annotatedentity',
            name='icd_code',
        ),
        migrations.RemoveField(
            model_name='annotatedentity',
            name='opcs_code',
        ),
        migrations.AlterField(
            model_name='projectmetrics',
            name='projects',
            field=models.ManyToManyField(blank=True, to='api.ProjectAnnotateEntities'),
        ),
        migrations.DeleteModel(
            name='ICDCode',
        ),
        migrations.DeleteModel(
            name='OPCSCode',
        ),
    ]
