# Generated by Django 2.2.28 on 2024-04-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_auto_20240215_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='metaannotation',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='project',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
