# Generated by Django 2.2.28 on 2024-05-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_auto_20240510_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectgroup',
            name='create_associated_projects',
            field=models.BooleanField(default=True, help_text='This only functions on new Project Group entries.  If creating a new Project Group and this is checked, it will create a ProjectAnnotateEntities for each annotator. If unchecked it will not create associated ProjectAnnotateEntities instead, leaving the admin to  manually configure groups of projects.'),
        ),
    ]
