# Generated by Django 2.2.28 on 2024-07-01 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_metacatmodel_modelpack'),
        ('api', '0078_alter_project_polymorphic_ctype'),
    ]

    operations = [
    ]
