# Generated by Django 5.0.6 on 2024-07-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_merge_20240701_2259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metatask',
            options={'ordering': ['ordering', 'name']},
        ),
        migrations.AlterModelOptions(
            name='metataskvalue',
            options={'ordering': ['ordering', 'name']},
        ),
        migrations.AddField(
            model_name='metatask',
            name='ordering',
            field=models.PositiveSmallIntegerField(default=0, help_text='the order in which the meta task will appear in the Trainer Annotation project screen'),
        ),
        migrations.AddField(
            model_name='metataskvalue',
            name='ordering',
            field=models.PositiveSmallIntegerField(default=0, help_text='the order in which the meta task value will appear in the Trainer Annotation project screen'),
        ),
    ]
