# Generated by Django 5.0.6 on 2024-07-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_alter_metatask_options_alter_metataskvalue_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metatask',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
