# Generated by Django 5.0.6 on 2024-08-28 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_alter_metatask_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metacatmodel',
            name='meta_task',
        ),
        migrations.AddField(
            model_name='metaannotation',
            name='predicted_meta_task_value',
            field=models.ForeignKey(blank=True, help_text='meta annotation predicted by a MetaAnnotationModel', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predicted_value', to='api.metataskvalue'),
        ),
        migrations.AddField(
            model_name='metatask',
            name='prediction_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.metacatmodel'),
        ),
        migrations.AddField(
            model_name='project',
            name='meta_cat_predictions',
            field=models.BooleanField(default=False, help_text='If MetaTasks are setup on the project and there are associated MetaCATModel instances, display these predictions in the interface to be validated / corrected'),
        ),
        migrations.AddField(
            model_name='projectannotateentities',
            name='model_pack',
            field=models.ForeignKey(blank=True, default=None, help_text='A MedCAT model pack. This will raise an exception if both the CDB and Vocab and ModelPack fields are set', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.modelpack'),
        ),
        migrations.AddField(
            model_name='projectgroup',
            name='meta_cat_predictions',
            field=models.BooleanField(default=False, help_text='If MetaTasks are setup on the project and there are associated MetaCATModel instances, display these predictions in the interface to be validated / corrected'),
        ),
        migrations.AddField(
            model_name='projectgroup',
            name='model_pack',
            field=models.ForeignKey(blank=True, default=None, help_text='A MedCAT model pack. This will raise an exception if both the CDB and Vocab and ModelPack fields are set', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.modelpack'),
        ),
        migrations.AlterField(
            model_name='metaannotation',
            name='validated',
            field=models.BooleanField(default=False, help_text='If an annotation is not '),
        ),
        migrations.AlterField(
            model_name='metacatmodel',
            name='meta_cat_dir',
            field=models.FilePathField(allow_folders=True, editable=False, help_text='The zip or dir for a MetaCAT model, not editable, is set via a model pack .zip upload'),
        ),
        migrations.AlterField(
            model_name='metacatmodel',
            name='name',
            field=models.CharField(help_text='The task name followed by the underlying model impl', max_length=100),
        ),
        migrations.AlterField(
            model_name='projectannotateentities',
            name='concept_db',
            field=models.ForeignKey(blank=True, help_text='The MedCAT CDB used to annotate / validate', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.conceptdb'),
        ),
        migrations.AlterField(
            model_name='projectannotateentities',
            name='tasks',
            field=models.ManyToManyField(blank=True, default=None, help_text='The set of MetaAnnotation tasks configured for this project, this will default to the set of Tasks configured in a ModelPack if a model pack is used for the project', to='api.metatask'),
        ),
        migrations.AlterField(
            model_name='projectannotateentities',
            name='vocab',
            field=models.ForeignKey(blank=True, help_text='The MedCAT Vocab used to annotate / validate', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.vocabulary'),
        ),
        migrations.AlterField(
            model_name='projectgroup',
            name='cdb_search_filter',
            field=models.ManyToManyField(blank=True, help_text='The CDB that will be used for concept lookup. This specific CDB should have been "imported" via the CDB admin screen', related_name='project_group_concept_source', to='api.conceptdb'),
        ),
        migrations.AlterField(
            model_name='projectgroup',
            name='concept_db',
            field=models.ForeignKey(blank=True, help_text='The MedCAT CDB used to annotate / validate', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.conceptdb'),
        ),
        migrations.AlterField(
            model_name='projectgroup',
            name='tasks',
            field=models.ManyToManyField(blank=True, default=None, help_text='The set of MetaAnnotation tasks configured for this project, this will default to the set of Tasks configured in a ModelPack if a model pack is used for the project', to='api.metatask'),
        ),
        migrations.AlterField(
            model_name='projectgroup',
            name='vocab',
            field=models.ForeignKey(blank=True, help_text='The MedCAT Vocab used to annotate / validate', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.vocabulary'),
        ),
    ]
