# Generated by Django 5.0.6 on 2024-08-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_remove_metacatmodel_meta_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='prepared_documents',
            field=models.ManyToManyField(blank=True, default=None, help_text='Set automatically on each prep of a document', related_name='prepared_documents', to='api.document'),
        ),
        migrations.AlterField(
            model_name='project',
            name='validated_documents',
            field=models.ManyToManyField(blank=True, default=None, help_text='Set automatically on each doc submission', to='api.document'),
        ),
    ]
