# Generated by Django 5.1.4 on 2025-01-30 11:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_modelpack_create_time_modelpack_last_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptdb',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z][a-zA-Z0-9_]*$', 'a-z for first character required. Alpahanumeric and _ thereafter are allowed for CDB names')]),
        ),
    ]
