# Generated by Django 5.1.4 on 2025-02-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_alter_conceptdb_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectannotateentities',
            name='deid_model_annotation',
            field=models.BooleanField(default=False, help_text='To indicate that this project is to collect De-ID Model annotations'),
        ),
        migrations.AddField(
            model_name='projectgroup',
            name='deid_model_annotation',
            field=models.BooleanField(default=False, help_text='To indicate that this project is to collect De-ID Model annotations'),
        ),
    ]
