# Generated by Django 5.1.11 on 2025-06-23 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_auto_20231211_1526'),
        ('api', '0089_projectannotateentities_deid_model_annotation_and_more'),
    ]

    operations = [
    ]
