# Generated by Django 2.2 on 2019-04-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('value', models.IntegerField(default=1)),
                ('acc', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UseCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(default='')),
                ('cuis', models.TextField(default='')),
                ('tuis', models.TextField(default='')),
                ('tokens', models.TextField(default='')),
                ('cntx_size', models.IntegerField(default=7)),
                ('cntx_tokens', models.TextField(default='')),
                ('other', models.TextField(default='')),
                ('filters', models.ManyToManyField(to='trainerapp.Filter')),
            ],
        ),
    ]
