# Generated by Django 2.2 on 2019-04-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainerapp', '0004_remove_usecase_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='usecase',
            name='folder',
            field=models.CharField(default='train', max_length=50),
        ),
    ]
