name: release-build

on:
  push:
    tags: [ 'v*.*.*' ]


jobs:
  # run tests / lint / etc. before building container image?

  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v4
        with:
          ref: 'master'

      - name: Release Tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Build
        env:
          IMAGE_TAG: ${{ env.RELEASE_VERSION }}
        run: |
          docker build -t cogstacksystems/medcat-trainer:$IMAGE_TAG -t cogstacksystems/medcat-trainer:latest webapp/.
          docker build -t cogstacksystems/medcat-trainer-nginx:$IMAGE_TAG -t cogstacksystems/medcat-trainer-nginx:latest nginx/.
      - name: Run Django Tests
        env:
          IMAGE_TAG: ${{ env.RELEASE_VERSION }}
        run: |
          # run tests
          docker run --rm cogstacksystems/medcat-trainer:$IMAGE_TAG python manage.py test

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to DockerHub
        env:
          IMAGE_TAG: ${{ env.RELEASE_VERSION }}
        run: |
          docker push cogstacksystems/medcat-trainer:$IMAGE_TAG
          docker push cogstacksystems/medcat-trainer:latest
          docker push cogstacksystems/medcat-trainer-nginx:$IMAGE_TAG
          docker push cogstacksystems/medcat-trainer-nginx:latest
